### ISSUE TITLE
Production example not working

### ISSUE THREAD

**Issue by Rodrigo-Vargas** [guisehn/caronas-unisc-api#1]
When access the link to production example provided in README file, the following error appears:

![image](https://cloud.githubusercontent.com/assets/11018846/11499590/2b21d2e4-980e-11e5-9313-2fdac936fdd6.png)

Url is: https://caronas-unisc.herokuapp.com/

**Comment by guisehn** [comment]
This is normal since this is an API for our Android app (not a website), so we don't have an endpoint for the root URL.

P.S.: Hahaha, I wasn't expecting anyone to see this project. We don't intend to maintain it after we deliver the project anyway. :)
